(ns translation-reader.screens.home
  (:require 
   ["package:flutter/material.dart" :as m]
   [cljd.flutter :as f]
   [translation-reader.widgets.menu :as menu]))
   
(defn screen []
  (f/widget
   :context ctx
   (m/Scaffold)
   .body
   (m/Padding
    .padding (m.EdgeInsets/only .top 40))
   (m/Row
    .children
    [(menu/view)
     (m/VerticalDivider
      .color (-> m/Theme (.of ctx) .-colorScheme .-primary))])))